source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DSRadialMenu_Example' do
  pod "DSRadialMenu", :path => "../"
end

target 'DSRadialMenu_Tests' do
  pod "DSRadialMenu", :path => "../"
end
